/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf9f6",
        "surface-dim": "#d6dbd5",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f0",
        "surface-container": "#edeeea",
        "surface-container-high": "#e6e9e4",
        "surface-container-highest": "#e0e4de",
        "surface-variant": "#e0e4de",
        "on-surface": "#2f3430",
        "on-surface-variant": "#5c605c",
        "on-background": "#2f3430",
        "primary": "#5f5e5e",
        "primary-dim": "#535252",
        "primary-container": "#e5e2e1",
        "primary-fixed": "#e5e2e1",
        "primary-fixed-dim": "#d6d4d3",
        "on-primary": "#faf7f6",
        "on-primary-container": "#525151",
        "on-primary-fixed": "#403f3f",
        "secondary": "#675e4c",
        "secondary-dim": "#5b5241",
        "secondary-container": "#efe1ca",
        "secondary-fixed": "#efe1ca",
        "secondary-fixed-dim": "#e0d3bc",
        "on-secondary": "#fff8f0",
        "on-secondary-container": "#5a513f",
        "on-secondary-fixed": "#473e2e",
        "tertiary": "#5f5f5f",
        "tertiary-dim": "#535353",
        "tertiary-container": "#f5f3f3",
        "tertiary-fixed": "#f5f3f3",
        "tertiary-fixed-dim": "#e7e5e4",
        "on-tertiary": "#fbf8f8",
        "on-tertiary-container": "#5c5c5b",
        "error": "#9f403d",
        "error-dim": "#4e0309",
        "error-container": "#fe8983",
        "on-error": "#fff7f6",
        "on-error-container": "#752121",
        "outline": "#777c77",
        "outline-variant": "#afb3ae",
        "inverse-surface": "#0d0f0d",
        "inverse-on-surface": "#9d9d9a",
        "inverse-primary": "#ffffff",
        "background": "#faf9f6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Manrope", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
      keyframes: {
        "slide-progress": {
          "0%": { transform: "scaleX(0)" },
          "100%": { transform: "scaleX(1)" },
        },
      },
      animation: {
        "slide-progress": "slide-progress 5s linear forwards",
      },
    },
  },
  plugins: [],
}
